# Generated by Django 5.0.2 on 2024-12-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtapp', '0002_board_todotask_user_cardcategory_card_boardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('column', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoTask',
        ),
    ]
