# Generated by Django 5.1.4 on 2025-01-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtapp', '0005_remove_card_board_remove_card_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
