# Generated by Django 5.1.4 on 2025-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtapp', '0008_boardmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='added_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
