# Generated by Django 5.0.2 on 2025-02-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtapp', '0010_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_by',
            field=models.CharField(max_length=20),
        ),
    ]
