# Generated by Django 5.1.4 on 2025-02-06 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtapp', '0011_alter_board_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bord_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wtapp.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
