# Generated by Django 5.1.4 on 2025-02-06 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtapp', '0012_task_bord_id_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bord_id',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='wtapp.board'),
        ),
    ]
